### ISSUE TITLE
Sound in a Prop

### ISSUE THREAD

**Issue by HowardBaxton** [nPoseTeam/nPose-Sound-Plugin#1]
I tried adding the sound plugin, sound files, notecard, and Prop plugin to a prop and use the new syntax to get the sounds to play.  It did not work.

I had to use LINKMSG|-2345.. to get it to work.

**Comment by LeonaMorro** [comment]
Did you change the lines in the .ìnit`file to:
```
PLUGINCOMMAND|SOUND_STOP|-2344|1
PLUGINCOMMAND|SOUND|-2346|1
PLUGINCOMMAND|SOUND_NC|-2347|1
```

**Comment by HowardBaxton** [comment]
Thank you, I figured I was over looking something very obvious.  This fixed MY issue.
